// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	ID          int64          `json:"id"`
	Username    string         `json:"username"`
	AddressLine sql.NullString `json:"address_line"`
	AddressTag  sql.NullString `json:"address_tag"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

type Favorite struct {
	ID       int64     `json:"id"`
	Username string    `json:"username"`
	FoodID   int64     `json:"food_id"`
	AddedAt  time.Time `json:"added_at"`
}

type Food struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Rate        int32  `json:"rate"`
	Discount    int32  `json:"discount"`
}

type Profile struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	Birthday    string `json:"birthday"`
	Nickname    string `json:"nickname"`
}

type User struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
