// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	AddressLine string `json:"address_line"`
	AddressTag  string `json:"address_tag"`
	PhoneNumber string `json:"phone_number"`
}

type Favorite struct {
	ID       int64     `json:"id"`
	Username string    `json:"username"`
	FoodID   int64     `json:"food_id"`
	AddedAt  time.Time `json:"added_at"`
}

type Food struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int32  `json:"price"`
	Rate        int32  `json:"rate"`
	Discount    int32  `json:"discount"`
	FoodTag     string `json:"food_tag"`
}

type Profile struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	Birthday    string `json:"birthday"`
	Nickname    string `json:"nickname"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
